from homeassistant.components.sensor import (
    SensorDeviceClass,
    SensorStateClass,
)

from homeassistant.helpers.entity import EntityCategory

from homeassistant.const import (
    PERCENTAGE,
    
)


ENTITY_DETAILS = {
    "current_5min_period_price": {
        "name": "Current 5min Period Price",
        "unit": "$",
        "icon": None,
        "device_class": SensorDeviceClass.MONETARY,
        "state_class": None,
        "display_precision": 4,
        "options": None,
        "mode": None,
        "category": None,
        "visible": True,
        "enabled": True,
        "data_set": "current_30min_forecast",
    },
    "current_30min_avg": {
        "name": "Current 30min Avg",
        "unit": "$",
        "icon": None,
        "device_class": SensorDeviceClass.MONETARY,
        "state_class": None,
        "display_precision": 4,
        "options": None,
        "mode": None,
        "category": None,
        "visible": True,
        "enabled": True,
        "data_set": "current_30min_forecast",
    },
    "current_30min_forecast": {
        "name": "Current 30min Forecast",
        "unit": "$",
        "icon": None,
        "device_class": SensorDeviceClass.MONETARY,
        "state_class": None,
        "display_precision": 4,
        "options": None,
        "mode": None,
        "category": None,
        "visible": True,
        "enabled": True,
        "data_set": "current_30min_forecast",
    },
    "current_30min_estimated": {
        "name": "Current 30min Estimated",
        "unit": "$",
        "icon": None,
        "device_class": SensorDeviceClass.MONETARY,
        "state_class": None,
        "display_precision": 4,
        "options": None,
        "mode": None,
        "category": None,
        "visible": True,
        "enabled": True,
        "data_set": "current_30min_forecast",
    },
    "current_cumulative_price": {
        "name": "Current Cumulative Price",
        "unit": "$",
        "icon": None,
        "device_class": SensorDeviceClass.MONETARY,
        "state_class": None,
        "display_precision": 0,
        "options": None,
        "mode": None,
        "category": None,
        "visible": True,
        "enabled": True,
        "data_set": "current_30min_forecast",
    },
    "current_percent_cumulative_price": {
        "name": "Current Percent Cumulative Price",
        "unit": PERCENTAGE,
        "icon": None,
        "device_class": None,
        "state_class": SensorStateClass.MEASUREMENT,
        "display_precision": 0,
        "options": None,
        "mode": None,
        "category": None,
        "visible": True,
        "enabled": True,
        "data_set": "current_30min_forecast",
    },
    "administered_price_cap": {
        "name": "Administered Price Cap",
        "unit": "$",
        "icon": None,
        "device_class": SensorDeviceClass.MONETARY,
        "state_class": None,
        "display_precision": 0,
        "options": None,
        "mode": None,
        "category": EntityCategory.DIAGNOSTIC,
        "visible": True,
        "enabled": True,
        "data_set": "current_30min_forecast",
    },
    "cumulative_price_threshold": {
        "name": "Cumulative Price Threshold",
        "unit": "$",
        "icon": None,
        "device_class": SensorDeviceClass.MONETARY,
        "state_class": None,
        "display_precision": 0,
        "options": None,
        "mode": None,
        "category": EntityCategory.DIAGNOSTIC,
        "visible": True,
        "enabled": True,
        "data_set": "current_30min_forecast",
    },
    "market_price_cap": {
        "name": "Market Price Cap",
        "unit": "$",
        "icon": None,
        "device_class": SensorDeviceClass.MONETARY,
        "state_class": None,
        "display_precision": 0,
        "options": None,
        "mode": None,
        "category": EntityCategory.DIAGNOSTIC,
        "visible": True,
        "enabled": True,
        "data_set": "current_30min_forecast",
    },
    "periods_of_current_30min": {
        "name": "5min periods of current 30min period",
        "unit": None,
        "icon": None,
        "device_class": None,
        "state_class": SensorStateClass.MEASUREMENT,
        "display_precision": 0,
        "options": None,
        "mode": None,
        "category": None,
        "visible": True,
        "enabled": True,
        "data_set": "current_30min_forecast",
    },
    "period_1": {
        "name": "Period 1",
        "unit": "$",
        "icon": None,
        "device_class": SensorDeviceClass.MONETARY,
        "state_class": None,
        "display_precision": 4,
        "options": None,
        "mode": None,
        "category": None,
        "visible": True,
        "enabled": True,
        "data_set": "current_price_window",
    },
    "period_2": {
        "name": "Period 2",
        "unit": "$",
        "icon": None,
        "device_class": SensorDeviceClass.MONETARY,
        "state_class": None,
        "display_precision": 4,
        "options": None,
        "mode": None,
        "category": None,
        "visible": True,
        "enabled": True,
        "data_set": "current_price_window",
    },
    "period_3": {
        "name": "Period 3",
        "unit": "$",
        "icon": None,
        "device_class": SensorDeviceClass.MONETARY,
        "state_class": None,
        "display_precision": 4,
        "options": None,
        "mode": None,
        "category": None,
        "visible": True,
        "enabled": True,
        "data_set": "current_price_window",
    },
    "period_4": {
        "name": "Period 4",
        "unit": "$",
        "icon": None,
        "device_class": SensorDeviceClass.MONETARY,
        "state_class": None,
        "display_precision": 4,
        "options": None,
        "mode": None,
        "category": None,
        "visible": True,
        "enabled": True,
        "data_set": "current_price_window",
    },
    "period_5": {
        "name": "Period 5",
        "unit": "$",
        "icon": None,
        "device_class": SensorDeviceClass.MONETARY,
        "state_class": None,
        "display_precision": 4,
        "options": None,
        "mode": None,
        "category": None,
        "visible": True,
        "enabled": True,
        "data_set": "current_price_window",
    },
    "period_6": {
        "name": "Period 6",
        "unit": "$",
        "icon": None,
        "device_class": SensorDeviceClass.MONETARY,
        "state_class": None,
        "display_precision": 4,
        "options": None,
        "mode": None,
        "category": None,
        "visible": True,
        "enabled": True,
        "data_set": "current_price_window",
    },
}