name: "Release"

on:
  release:
    types:
      - "published"

permissions: {}

jobs:
  release:
    name: "Release"
    runs-on: "ubuntu-latest"
    permissions:
      contents: write
    steps:
      - name: "Checkout the repository"
        uses: "actions/checkout@v4.2.2"

      - name: "ZIP the integration directory"
        shell: "bash"
        run: |
          cd "${{ github.workspace }}/custom_components/aemo_nem"
          zip aemo_nem.zip -r ./

      - name: "Upload the ZIP file to the release"
        uses: "softprops/action-gh-release@v2.3.2"
        with:
          files: ${{ github.workspace }}/custom_components/aemo_nem/aemo_nem.zip
